Repository goorea/MBTo, pull requests merged in 2021-05, with the labels that each got.

#1 [style] 폴더 구조 변경
  __tests__/App-test.tsx
  index.js
  src/App.tsx
Labels: style

#2 [style] eslint 룰 추가 및 적용
  .eslintrc.js
  .prettierrc.js
  __tests__/App-test.tsx
  index.js
  metro.config.js
  src/App.tsx
Labels: style

#3 [style] Alias Resolve 설정
  babel.config.js
  package.json
  tsconfig.json
  yarn.lock
Labels: style

#4 [fix] ios flipper로 인한 빌드 이슈
  ios/MBTo.xcodeproj/project.pbxproj
  ios/MBTo.xcworkspace/contents.xcworkspacedata
  ios/MBTo.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Podfile
  ios/Podfile.lock
Labels: bug

#5 [feat] 배달의민족 폰트들 추가
  android/app/src/main/assets/fonts/BMHANNAAir.ttf
  android/app/src/main/assets/fonts/BMHANNAPro.ttf
  ios/MBTo.xcodeproj/project.pbxproj
  ios/MBTo/Info.plist
  react-native.config.js
  src/assets/fonts/BMHANNAAir.ttf
  src/assets/fonts/BMHANNAPro.ttf
  src/components/Text.tsx
Labels: enhancement

#6 [style] 패키지 이름 및 앱 버전 변경
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/goorea/mbto/MainActivity.java
  android/app/src/main/java/com/goorea/mbto/MainApplication.java
  ios/MBTo.xcodeproj/project.pbxproj
  ios/MBTo/Info.plist
Labels: style

#9 [feat] vector-icons 패키지 추가
  android/app/build.gradle
  ios/MBTo.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/App.tsx
  yarn.lock
Labels: duplicate, enhancement

#8 [feat] react-native-fast-image 패키지 추가
  android/app/proguard-rules.pro
  package.json
  yarn.lock
Labels: enhancement

#11 [fix] package.json 신택스 수정
  package.json
Labels: bug

#12 [feat] vector-icons 패키지 재설치
  android/app/src/main/assets/fonts/AntDesign.ttf
  android/app/src/main/assets/fonts/Entypo.ttf
  android/app/src/main/assets/fonts/EvilIcons.ttf
  android/app/src/main/assets/fonts/Feather.ttf
  android/app/src/main/assets/fonts/FontAwesome.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  android/app/src/main/assets/fonts/Fontisto.ttf
  android/app/src/main/assets/fonts/Foundation.ttf
  android/app/src/main/assets/fonts/Ionicons.ttf
  android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  android/app/src/main/assets/fonts/MaterialIcons.ttf
  android/app/src/main/assets/fonts/Octicons.ttf
  android/app/src/main/assets/fonts/SimpleLineIcons.ttf
  android/app/src/main/assets/fonts/Zocial.ttf
  ios/MBTo.xcodeproj/project.pbxproj
  ios/MBTo/Info.plist
  ios/Podfile.lock
  src/App.tsx
Labels: enhancement

#10 [feat] react-navigation 추가
  ios/Podfile.lock
  package.json
  src/App.tsx
  src/navigations/MainNavigation.tsx
  src/screens/FeedScreen.tsx
  src/screens/HotScreen.tsx
  src/screens/MyScreen.tsx
  src/screens/SearchScreen.tsx
  src/types/navigations.ts
  yarn.lock
Labels: enhancement

#18 [feat] Feed screen
  index.js
  ios/Podfile.lock
  package.json
  src/components/Comment/CommentContainer.tsx
  src/components/Comment/CommentPresenter.tsx
  src/components/Comment/index.ts
  src/components/cards/PostCard/PostCardContainer.tsx
  src/components/cards/PostCard/PostCardPresenter.tsx
  src/components/cards/PostCard/index.ts
  src/functions.ts
  src/plugins/moment.ts
  src/screens/Feed/FeedContainer.tsx
  src/screens/Feed/FeedPresenter.tsx
  src/screens/Feed/index.ts
  src/types/instances.ts
  yarn.lock
Labels: enhancement

#19 [feat] 프로젝트 테마 설정
  index.js
  ios/Podfile.lock
  src/App.tsx
  src/components/Comment/CommentPresenter.tsx
  src/components/Text.tsx
  src/components/cards/PostCard/PostCardContainer.tsx
  src/components/cards/PostCard/PostCardPresenter.tsx
  src/components/cards/PostCard/index.ts
  src/navigations/MainNavigation.tsx
  src/navigations/TabNavigation.tsx
  src/screens/FeedScreen.tsx
  src/themes.ts
Labels: enhancement, style

#20 [feat] 플래시 메세지 기능
  ios/Podfile.lock
  package.json
  src/App.tsx
  src/components/FlashMessage.tsx
  src/functions.ts
  yarn.lock
Labels: enhancement

#21 [feat] ThemeContext 도입
  src/App.tsx
  src/components/Comment/CommentPresenter.tsx
  src/components/Text.tsx
  src/components/cards/PostCard/PostCardPresenter.tsx
  src/contexts/ThemeContext.tsx
  src/navigations/MainNavigation.tsx
  src/navigations/TabNavigation.tsx
  src/themes.ts
Labels: enhancement
